version: '3.4'

services:
  featuredb:
    container_name: featuredb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - feature_data:/data/db

  productdb:
    container_name: productdb
    restart: always
    ports:
        - "27018:27017"
    volumes:
        - product_data:/data/db 

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  featureswitch.api:
    container_name: featureswitch.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://featuredb:27017"      
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - featuredb
      - rabbitmq
    ports:
      - "8000:80" 



  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://productdb:27018"  
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - productdb
      - rabbitmq
    ports:
      - "8001:80"

